import os
import yaml
from datetime import datetime


def format_date(date_val):
    if isinstance(date_val, str):
        dt = datetime.strptime(date_val, "%Y-%m-%d")
    elif isinstance(date_val, datetime):
        dt = date_val
    else:  # e.g., datetime.date
        dt = datetime.combine(date_val, datetime.min.time())
    return dt.strftime("%A, %B %d, %Y")

post_info = []
for folder in os.listdir("./posts/"):
    folder_path = os.path.join("./posts", folder)
    if os.path.isdir(folder_path):
        with open(os.path.join(folder_path, 'index.qmd'), 'r', encoding='utf-8') as f:
            lines = f.readlines()

        if not lines or not lines[0].strip() == '---':
            pass  # No YAML front matter

        else:
            # Extract YAML between the first pair of '---' lines
            yaml_lines = []
            for line in lines[1:]:
                if line.strip() == '---':
                    break
                yaml_lines.append(line)
            yaml_text = ''.join(yaml_lines)
            yaml_data = yaml.safe_load(yaml_text)
            if yaml_data and 'title' in yaml_data and 'date' in yaml_data:
                if 'draft' in yaml_data and yaml_data['draft']:
                    print(f"Not including draft post: {yaml_data['title']} in front page listing")
                    continue
                post_info.append({
                    'title': yaml_data['title'],
                    'date': yaml_data['date'],
                    'folder': folder, 
                    'description': yaml_data['description']
                })

post_info.sort(key=lambda x: x['date'], reverse=True)

with open("./components/_post_list.md", "w", encoding="utf-8") as f:
    f.write("<!-- This file is auto-generated by assemble_posts.py -->\n\n")
    for post in post_info:
        f.write(f"- [{post['title']}](/posts/{post['folder']}/)" + "{.lead}  \n")
        f.write(f"  [{format_date(post['date'])}]" + "{.small .text-muted}  \n")
        f.write(f"  {post['description']}  \n")



    # Attempt at a groovier link-container.
    # for post in post_info:
    #     text = "<div class='post-link-container'>\n"
    #     text += f"<a href='/posts/{post['folder']}/' class='post-link'>\n"
    #     text += f"<h3 class='post-title'>{post['title']}</h2>\n"
    #     text += f"<p class='post-date'>{post['date']}</p>\n"
    #     # text += f"{post.keys()}"
    #     text += f"<p class='post-description'>{post['description']}</p>\n"
    #     text += "</a>\n"
    #     text += "</div>\n\n"
    #     f.write(text)


