import os
import yaml

post_info = []
for folder in os.listdir("./posts/"):
    folder_path = os.path.join("./posts", folder)
    if os.path.isdir(folder_path):
        with open(os.path.join(folder_path, 'index.qmd'), 'r', encoding='utf-8') as f:
            lines = f.readlines()

        if not lines or not lines[0].strip() == '---':
            pass  # No YAML front matter

        else:
            # Extract YAML between the first pair of '---' lines
            yaml_lines = []
            for line in lines[1:]:
                if line.strip() == '---':
                    break
                yaml_lines.append(line)
            yaml_text = ''.join(yaml_lines)
            yaml_data = yaml.safe_load(yaml_text)
            if yaml_data and 'title' in yaml_data and 'date' in yaml_data:
                if 'draft' in yaml_data and yaml_data['draft']:
                    continue
                post_info.append({
                    'title': yaml_data['title'],
                    'date': yaml_data['date'],
                    'folder': folder
                })

post_info.sort(key=lambda x: x['date'], reverse=True)

with open("./components/_post_list.md", "w", encoding="utf-8") as f:
    f.write("<!-- This file is auto-generated by assemble_posts.py -->\n\n")
    for post in post_info:
        f.write(f"- [{post['title']}](/posts/{post['folder']}/)\n")


