---
title: Past reports on compensation at UNCA 
date: 2026-10-05
date-format: "MMMM, YYYY"
author:
  - family: McClure
    given: Mark

format:
  html: 
    page-layout: article
  pdf: 
    toc: false
    output-file: PastReportsOnCompensationAtUNCA
    echo: false
---


Here are all the written reports on compensation at UNCA that I'm aware of, ordered chronologically by release date. There's also a little of my own commentary.

Note that, with the exception of a couple of things that I wrote, these reports are generally PDFs lying on UNCA's Google Drive.

0. [Task Force on Faculty Salary and Equity](https://drive.google.com/file/d/1W4T64jRPmX6uAsou9K9f0ktizBhU-IIw/view?usp=drive_link){target=_blank} - Jan 2018  
   <div class="note-comments">
   
    This $\text{zero}^{\text{th}}$ report predates my participation and is a bit different from the remaining documents in that it is not primarily motivated by concern with the level of compensation at UNCA. It focuses more on equity between and within departments and with procedures for maintaining fairness moving forward. The report does note, however, that "substantive salary increases had not been available for several years".

   </div>
1. [Task Force on Total Compensation](https://drive.google.com/file/d/116rwbrxLTb8bJqdNji5lSnAYNxLAULkw/view?usp=drive_link){target=_blank} - May 2019  
    <div class="note-comments">

     By Fall of 2018, concern over the *level* of compensation at UNCA had grown and a new task force to study that specific issue was formed. I was appointed to that task force as a member of the Institutional Development Committee of Faculty Senate.

     This report focused on salary and benefits for both faculty and staff at UNCA. It compared that compensation to the cost of living as measured by the consumer price index for Southeast urban areas. We had good data on both of those going back a couple of decades so we were able to illustrate how our effective compensation has decreased over time.

     There were several issues with this study, such as 

     - We did not study compensation with our peers in either the system or with similar institutions, simply because that was not part of our charge.
     - We did not study the relationship between compensation and housing costs in Asheville. We would've liked to study this but the data is simply hard to come by.
    
    </div>

2. [UNCA Salaries and Housing in Asheville](https://drive.google.com/file/d/1MCtSX_TIy-50uICnoeBjNd-aL510HFBZ/view?usp=drive_link){target=_blank} - June 2019  
   <div class="note-comments">

   When the work of the prior Task Force on Total Compensation was nearing completion, I happened to stumble upon some outstanding data on housing costs in Asheville via a personal relationship with people at Mosaic Realty. I used that data to compare the rate of growth of compensation at UNCA with the cost of home ownership going back a decade and a half. This document is the result of that work.

   While this work was too late to appear in the immediately preceding task force report, it does appear as an addendum.

   </div>

\newpage 

3. [Informal report on Faculty Compensation](https://drive.google.com/file/d/1GL8LWyk4u2_JML-D61Ww2utJ0i0pFLe0/view?usp=drive_link){target=_blank} - Feb 2022  
   <div class="note-comments">

   In November of 2021, Chancellor Cable announced the "historic" news that the newly passed state budget included a 7% raise to be split over the next two years. Unfortunately, the truly "historic" part was that a budget had finally been passed, we had not received raises for some time, and that 7% over two years did not even keep up with inflation. After email discussions over these issues, as was common on faculty_official@unca.edu at that time, a group of faculty formed an independent working group to study and make a stronger statement on these issues.

   This report was presented to FWDC in Feb 2022 and 
   - Focuses on faculty, while acknowledging the situation is dire for staff as well,
   - Is a stronger statement, describing the situation as a "crisis",
   - Refers to the prior task force data on salaries and provides new assessments using BLS data,
   - Addresses morale via surveys like [Harvard's COACHE](https://coache.gse.harvard.edu/faculty-job-satisfaction-survey){target=_blank} and the UNC System Employee Engagement Survey,
   - Contains a list of asks of the administration including 
     - the commitment to secure cost-of-living adjustments and 
     - to develop the means to improve salaries at UNC Asheville
   
   The authors of this report are not identified, though it's signed by 58 faculty members.

   </div>
4. [UNCA Faculty Salaries](https://marksmath.org/writ/UNCAFacultySalariesApr2022.html){target=_blank} - Apr 2022  
   <div class="note-comments">

   I was a member of the informal working group and contributed a fair amount of data and analysis. This webpage represents my own analysis of the issues with a focus on
   - comparisons with multiple cohorts and evolution over time,
   - effect on faculty retention, and 
   - salary compression (it sucks being old, you know).

   </div>
5. [Revitalization Plan](https://drive.google.com/file/d/1rl1Ew5Yj2Jky5fjTLO8RXuSiMTh7LB_y/view?usp=drive_link){target=_blank} - Sep 2022  
   <div class="note-comments">

   The compensation issues at UNCA are part of broader financial issues involving enrollment, tuition, state appropriations and other issues generally at the state level. Spearheaded by former Chancellor Nancy Cable, former Provost Kai Campbell, and former VC for Financial Affairs John Pierce, the "Revitalization Plan" was an attempt to address all of these. This is their presentation document as of Sep 2022.

   This document states several challenges that UNCA has faced historically including 
   - turnover in leadership,
   - biases in the funding model, and
   - cost of living in Asheville.

   \newpage
   
   The document also proposes a comprehensive plan involving 
   - increased enrollment,
   - replacement of key staff members,
   - budget discipline,
   - a fundraising campaign, and 
   - investment from the state.

   Two years of significant state funding were obtained and put toward something, I guess. The Asheville Ideas Fest arose from philanthropic donations.
  <div style="font-size: 1.25em; padding: 10px;">
   *Note*: While enrollment is part of this strategy, it's important to note that the plan states quite clearly that "enrollment alone won't provide the net revenue to close the shortfall". It goes further to say "Enrollment up to 4,000 students will yield roughly $5M towards a $24M shortfall." This statement is based on a detailed study by John Pierce and does not appear to be accounted for in current strategies. According to a recent conversation I had with John, enrollment up to 5000 still comes nowhere close to closing the shortfall.
  </div>
   </div>

6. [First Compensation Committee report](https://drive.google.com/file/d/1Xw1s8al40-dzUccnilEseeu3_BPtJMFp/view?usp=drive_link){target=_blank} - Feb 2023  
   <div class="note-comments">

   In response to the informal working group, a standing committee was formed to continue to monitor salaries and compensation at UNCA. I was the first chair of that committee and this is our first report.

   We generally approved of the Revitalization Plan and endorsed it. We particularly liked the fact that the plan makes a strong case that UNCA is simply underfunded by the state. We were also happy to see two years of investment coming to UNCA but were deeply disappointed to see absolutely no investment in current faculty and staff.

   </div>
7. [Slides for committee presentation to Staff Council](https://marksmath.org/presentations/CompensationSlides2023/){target=_blank} - Mar 2023  
   <div class="note-comments">
   
   As chair of the Compensation Committee, I presented our findings to both Faculty Senate and Staff Council. These are the slides I used for those presentations.

   </div>